//
// Created by DripTooHard on 27-09-2023.
//

#ifndef PBT_BLEMACROS_H
#define PBT_BLEMACROS_H

#define SERVER_DEVICE_NAME "aBcDeF"

#define BATTERY_PWR_VLTG_CHAR_UUID "0002"
#define BATTERY_PWR_WARN_CHAR_UUID "0003"
#define BATTERY_PWR_SRVI_UUID "BA79"

#define SWC_SRVI_UUID "3A7E"
#define SWC_VWC_CHAR_UUID "0007"
#define SWC_VWC_TSTAMP_CHAR_UUID "0008"

#define TEMP_SRVI_UUID "7E89"
#define TEMP_READ_CHAR_UUID "0011"
#define TEMP_READ_FREQ_CHAR_UUID "0012"

#endif //PBT_BLEMACROS_H
