//
// Created by DripTooHard on 09-07-2023.
//

#ifndef PROTOBLETEST_SENSOR_SETTINGS_H
#define PROTOBLETEST_SENSOR_SETTINGS_H

#define SWC_SENSR_READ_PIN 35
#define SWC_SENSR_PWR_PIN 4

#endif //PROTOBLETEST_SENSOR_SETTINGS_H
