//
// Created by DripTooHard on 08-10-2023.
//

#ifndef PBT_STATES_MACROS_H
#define PBT_STATES_MACROS_H

#define STATE_IDLE 0
#define STATE_LISTENING 1
#define STATE_VALUE_RECEIVED 2
#define STATE_PRINTING 3

//LED pins
#define BLE_FLASH_PIN 32
#define XPERIMENT_ON_PIN 25
#define XPERIMENT_ARRAY_FULL 33

#define TIME_DELAY_AFTER_PRINTING_mS 5000
#define PRINTING_ON_TRIGGER_PIN 19

#define XPERIMENT_ON_TRIGGER_PIN 18

#define RESTART_TRIGGER_PIN 17

#endif //PBT_STATES_MACROS_H
