//
// Created by DripTooHard on 08-10-2023.
//

#ifndef PBT_STATES_MACROS_H
#define PBT_STATES_MACROS_H

#define STATE_IDLE 0
#define STATE_LISTENING 1
#define STATE_VALUE_RECEIVED 2
#define STATE_PRINTING 3

#define PRINT_INTERRUPT_PIN

#endif //PBT_STATES_MACROS_H
