//
// Created by DripTooHard on 02-10-2023.
//

#ifndef PBT_FORMATTING_MACROS_H
#define PBT_FORMATTING_MACROS_H

#define END_OF_VALUE_CHAR 44
#define END_OF_STRING_CHAR 11

#endif //PBT_FORMATTING_MACROS_H
