//
// Created by DripTooHard on 02-10-2023.
//

#ifndef PBT_FORMATTING_MACROS_H
#define PBT_FORMATTING_MACROS_H

#define END_OF_VALUE_CHAR 44
#define END_OF_STRING_CHAR 11

#define MAX_DATALOGGING_RETRIES 5
#define mS_TIME_BETWEEN_DATALOGS 750

#define SIZE_OF_SWC_AFTER_FORMATTING 6 //XX.XX\0
#define SIZE_OF_TIMESTAMP_AFTER_FORMATTING 4
#define SIZE_OF_TIMESTAMP_AFTER_TURNING_INTO_UCHAR 4

#define NR_READS_PER_45_DAYS 2160
#define ERROR_MARGIN_PER_45_DAYS 100

#define SWC_VALUE_ARRAY_SIZE (NR_READS_PER_45_DAYS+ERROR_MARGIN_PER_45_DAYS)*SIZE_OF_SWC_AFTER_FORMATTING
#define TIMESTEP_VALUE_ARRAY_SIZE (NR_READS_PER_45_DAYS+ERROR_MARGIN_PER_45_DAYS)*SIZE_OF_TIMESTAMP_AFTER_FORMATTING

#define TIMESTEP_VALUE_ARRAY_PATH "/tstep_vray"
#define SWC_VALUE_ARRAY_PATH "/SWC_vray.txt"

#endif //PBT_FORMATTING_MACROS_H
